// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace SkillGameplayTags
{
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_A);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_B);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_C);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_D);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_E);

	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_A);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_B);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_C);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_D);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_E);
}