// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

class UAbilitySystemComponent;

namespace SpyGameplayTags
{
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_A);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_B);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_C);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_D);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_E);

	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_A);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_B);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_C);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_D);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_E);

	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Actor_Fire);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Actor_Heal);

	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Static_Hit);

	SKILLPROJECT_API FGameplayTag GetActiveSkillTag(const UAbilitySystemComponent* ASC);
}