// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace SpyGameplayTags
{
	//# 잠금 관련
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Lock_Input_All);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Lock_Input_Move);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Lock_Input_Look);

	//# 상태 초기화 관련
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvailable);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);

	//# 캐릭터 클래스
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Class_Normal);

	//# 캐릭터 생존 상태
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Survival_Alive);

	//# 기본 입력 슬롯
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Native_Move);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Native_Look);

	//# GAS 입력 슬롯
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Skill_1);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Skill_2);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Skill_3);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Skill_4);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Skill_5);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Skill_6);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Skill_7);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Skill_8);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Skill_9);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Skill_10);

	//# 액션 스킬
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Action_A);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Skill_Action_A);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Notify_Skill_Action_A);

	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Action_B);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Skill_Action_B);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Notify_Skill_Action_B);

	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Action_C);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Skill_Action_C);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Notify_Skill_Action_C);

	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Action_D);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Skill_Action_D);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Notify_Skill_Action_D);

	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Action_E);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Skill_Action_E);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Notify_Skill_Action_E);

	//# 이동 스킬
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Move_Vault);

	//# Actor 이펙트
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Actor_Fire);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Actor_Heal);

	//# Static 이펙트
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Static_Hit);

	//# 언리얼 기본 무브먼트
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Walking);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_NavWalking);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Falling);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Swimming);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Flying);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Custom);

	//# 커스텀 무브먼트
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_WallClimb);

	SKILLPROJECT_API extern const TMap<uint8, FGameplayTag> MovementModeTagMap;
	SKILLPROJECT_API extern const TMap<uint8, FGameplayTag> CustomMovementModeTagMap;
}