// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "GameplayTagContainer.h"
#include "NativeGameplayTags.h"
#include "SKGameplayTags.h"

//# ============================================================
//# SpyGameplayTags — SkillProject 게임 전용 태그
//# SKGameplayTags(플러그인 공통)를 확장한 자식 태그를 정의합니다.
//# 이 헤더를 포함하면 SKGameplayTags도 함께 사용할 수 있습니다.
//# ============================================================
namespace SpyGameplayTags
{
	//# 락 태그
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Lock_Input_All);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Lock_Input_Move);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Lock_Input_Look);

	//# 캐릭터 초기화 태그
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvailable);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);

	//# 캐릭터 클래스
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Class_AI);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Class_Normal);

	//# 캐릭터 상태
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Targeting);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Movement_Normal);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Movement_Climb);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Grapple);

	//# 기본 입력 태그
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Native_Move);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Native_Look);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Native_CursorToggle);

	//# GAS 입력 태그
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Skill_1);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Skill_2);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Skill_3);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Skill_4);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Skill_5);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Skill_6);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Skill_7);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Skill_8);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Skill_9);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Skill_10);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Parry);

	//# 액션 스킬
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Action_A);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Skill_Action_A);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Notify_Skill_Action_A);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Skill_Action_A);

	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Action_B);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Skill_Action_B);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Notify_Skill_Action_B);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Skill_Action_B);

	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Action_C);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Skill_Action_C);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Notify_Skill_Action_C);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Skill_Action_C);

	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Action_D);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Skill_Action_D);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Notify_Skill_Action_D);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Skill_Action_D);

	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Action_E);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Skill_Action_E);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Notify_Skill_Action_E);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Skill_Action_E);

	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Action_F);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Skill_Action_F);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Notify_Skill_Action_F);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Skill_Action_F);

	//# 이동 스킬
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Move_Vault);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Move_Climb);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Move_HangUp);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Move_Jump);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Move_GrappleHook);

	//# GAS 입력 태그 확장
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Skill_11);

	//# 유틸 스킬
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Util_Death);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Util_Combo1);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Util_Combo2);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Util_Combo3);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Util_Combo4);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Util_Combo5);

	//# 콤보 태그 5종 묶음. 부모 태그(Skill.Util) 매칭은 Skill.Util.Death 까지 걸리므로 쓸 수 없다
	SKILLPROJECT_API const FGameplayTagContainer& GetComboTags();

	//# Actor 게임플레이큐
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Actor_Attack);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Actor_Target);

	//# Static 게임플레이큐
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Static_Hit);

	//# 이동 모드 기본 태그
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Walking);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_NavWalking);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Falling);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Swimming);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Flying);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Custom);

	//# 커스텀 이동 모드 태그
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_WallClimb);

	//# SetByCaller 데이터 태그
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Experience_Gain);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Level_MaxHealthGrowth);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Level_MaxManaGrowth);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Cost_Mana);

	//# 미션 진행 이벤트 태그
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Mission_Kill);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Mission_Combo);
	SKILLPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Mission_Level);

	SKILLPROJECT_API extern const TMap<uint8, FGameplayTag> MovementModeTagMap;
	SKILLPROJECT_API extern const TMap<uint8, FGameplayTag> CustomMovementModeTagMap;
}
